# Generated by Django 5.1.1 on 2024-10-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("props", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="faq",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
