# Generated by Django 5.1.1 on 2025-03-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="client_id",
            field=models.TextField(null=True),
        ),
    ]
