# Generated by Django 5.0.7 on 2024-08-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("USER", "User"), ("APP", "App")],
                default="USER",
                max_length=10,
            ),
        ),
    ]
