# Generated by Django 5.1.1 on 2025-05-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
