repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.1
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format

# assuming
#   - pytest is in your venv (called .venv)
#   - your tests are in a folder called tests
- repo: local
  hooks:
  - id: pytest
    name: pytest
    entry: ./venv/bin/pytest app/apps/tests
    language: system
    types: [python]
    pass_filenames: false
    always_run: true
