services:
  fuatilia-api:
    image: fuatilia-api:0.0.1
    build: .
    ports:
      - "8000:8000"
    environment:
      - TRACING_EXPORTER_ENDPOINT=${TRACING_EXPORTER_ENDPOINT}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      mode: replicated
      replicas: 1

  redis:
    image: redis:7.4.1
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 10s
      retries: 5
    command: redis-server --loglevel verbose
    deploy:
      mode: replicated
      replicas: 1

# FOR TESTS
  # redis-insight:
  #   image: redis/redisinsight:latest
  #   restart: always
  #   ports:
  #     - "5540:5540"
