version: 2.1

jobs:
  trigger-ci-pipeline:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Trigger central CI/CD pipeline
          command: |
            curl -u ${CIRCLECI_API_TOKEN}: \
              -X POST https://circleci.com/api/v2/project/${PROJECT_SLUG}/pipeline/run \
              -H 'Content-Type: application/json' \
              -d '{
                "definition_id": ${PIPELINE_DEFINITION_ID},
                "checkout": {"branch": "main"},
                "config": {"branch", "main"},
                "parameters": {
                  "target_repo": "fuatilia",
                  "deploy_env": "dev",
                  "triggered_by": "API call from fuatilia"
                }
              }'

workflows:
  trigger-central:
    jobs:
      - trigger-ci-pipeline
