global:
 scrape_interval: 10s
 evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']

  - job_name: 'fuatilia-api'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
    - targets: ['fuatilia-api:8000']
      labels:
        alias: "api"
