# Generated by Django 5.0.7 on 2024-08-08 18:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("FIRST_READING", "First Reading"),
                            ("SECOND_READING", "Second Reading"),
                            ("PASSED", "Passed"),
                            ("FAILED", "Failed"),
                            ("IN_PROGRESS", "In Progress"),
                            ("ASCENTED", "Ascented"),
                        ],
                        default="IN_PROGRESS",
                        max_length=20,
                    ),
                ),
                ("sponsored_by", models.CharField(max_length=100)),
                ("supported_by", models.CharField(max_length=100, null=True)),
                (
                    "house",
                    models.CharField(
                        choices=[
                            ("NATIONAL", "National"),
                            ("SENATE", "Senate"),
                            ("ALL", "All"),
                        ],
                        max_length=20,
                    ),
                ),
                ("summary", models.CharField(max_length=100, null=True)),
                ("summary_created_by", models.CharField(max_length=100, null=True)),
                ("summary_upvoted_by", models.CharField(max_length=100, null=True)),
                ("summary_downvoted_by", models.CharField(max_length=100, null=True)),
                ("final_date_voted", models.CharField(max_length=100, null=True)),
                ("topics_in_the_bill", models.CharField(max_length=200, null=True)),
                ("file_url", models.CharField(max_length=100, null=True)),
                ("updated_by", models.CharField(max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "bill",
                "indexes": [
                    models.Index(
                        fields=["summary", "topics_in_the_bill"],
                        name="bills_bill_summary_7d989d_idx",
                    )
                ],
            },
        ),
    ]
