# Generated by Django 5.0.7 on 2024-08-14 18:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bills", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bill",
            options={"ordering": ["-created_at"], "verbose_name": "bill"},
        ),
    ]
