# Generated by Django 5.1.1 on 2025-05-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bills", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bill",
            name="sponsored_by",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="bill",
            name="supported_by",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
