# Generated by Django 5.1.1 on 2024-10-17 10:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bills", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bill",
            old_name="updated_by",
            new_name="last_updated_by",
        ),
    ]
