# Generated by Django 5.0.7 on 2024-08-08 18:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Representative",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("MP", "Mp"),
                            ("SENATOR", "Senator"),
                            ("WOMEN_REP", "Women Rep"),
                            ("MCA", "Mca"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "position_type",
                    models.CharField(
                        choices=[("ELECTED", "Elected"), ("NOMINATED", "Nominated")],
                        max_length=10,
                    ),
                ),
                (
                    "house",
                    models.CharField(
                        choices=[
                            ("NATIONAL", "National"),
                            ("SENATE", "Senate"),
                            ("ALL", "All"),
                        ],
                        max_length=10,
                    ),
                ),
                ("area_represented", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=15, null=True)),
                ("image_url", models.CharField(max_length=100, null=True)),
                ("gender", models.CharField(max_length=2)),
                ("representation_summary", models.JSONField(null=True)),
                ("pending_update_json", models.JSONField(null=True)),
                ("updated_by", models.CharField(max_length=30, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "representatives",
                "db_table": "representatives",
                "ordering": ["-created_at"],
            },
        ),
    ]
