# Generated by Django 5.1.1 on 2025-03-03 17:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Representative",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=100, unique=True)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("MP", "Mp"),
                            ("SENATOR", "Senator"),
                            ("WOMEN_REP", "Women Rep"),
                            ("MCA", "Mca"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "position_class",
                    models.CharField(
                        choices=[("ELECTED", "Elected"), ("NOMINATED", "Nominated")],
                        max_length=10,
                    ),
                ),
                (
                    "house",
                    models.CharField(
                        choices=[
                            ("NATIONAL", "National"),
                            ("SENATE", "Senate"),
                            ("ALL", "All"),
                        ],
                        max_length=10,
                    ),
                ),
                ("area_represented", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=15, null=True)),
                ("image_url", models.CharField(max_length=250, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("FEMALE", "Female"),
                            ("MALE", "Male"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "current_parliamentary_roles",
                    models.CharField(max_length=100, null=True),
                ),
                ("representation_summary", models.JSONField(null=True)),
                ("pending_update_json", models.JSONField(null=True)),
                ("version", models.IntegerField(default=0)),
                ("last_updated_by", models.CharField(max_length=30, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "representatives",
                "db_table": "representatives",
                "ordering": ["-created_at"],
            },
        ),
    ]
