# Generated by Django 5.1.1 on 2025-03-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("representatives", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="representative",
            name="gender",
            field=models.CharField(
                choices=[("FEMALE", "Female"), ("MALE", "Male"), ("OTHER", "Other")],
                max_length=10,
                null=True,
            ),
        ),
    ]
