# Generated by Django 5.1.1 on 2025-03-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("representatives", "0002_alter_representative_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="representative",
            name="last_updated_by",
            field=models.CharField(max_length=40, null=True),
        ),
    ]
