# Generated by Django 5.1.1 on 2025-01-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "representatives",
            "0002_rename_updated_by_representative_last_updated_by_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="representative",
            name="current_parliamentary_roles",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
