# Generated by Django 5.1.1 on 2025-01-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("representatives", "0003_representative_current_parliamentary_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="representative",
            name="image_url",
            field=models.CharField(max_length=250, null=True),
        ),
    ]
