name: branch-push
run-name: Run initated by ${{ github.actor }}
on:
  pull_request:
    branches:
      - main
      - sandbox
      - uat
      - dev
jobs:
  PR-checker:
    runs-on: ubuntu-latest
    env:
        ENVIRONMENT: dev
        SECRET_KEY: secret_key

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
      - name: Check lint with Ruff
        run: |
          pip install ruff
          ruff check .
      - name: Test with logs
        run: |
          mkdir logs
          echo "Logs from building" > logs/test.log
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pip install pytest pytest-cov
          pytest --log-disable=app_logger --doctest-modules --junitxml=junit/test-results.xml
        # --cov=com --cov-report=xml --cov-report=html
        env: |
          DJANGO_SETTINGS_MODULE: settings.production
