name: Trigger PR Checks

on:
  pull_request:
    branches: [main, sandbox, uat, dev]

jobs:
  trigger-pr-checks:
    runs-on: ubuntu-latest
    steps:
      # Generate token from GitHub App
      - name: Generate App Token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      # Trigger checks in infra repo
      - name: Trigger infra checks
        uses: actions/github-script@v6
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: 'Fuatilia',
              repo: 'ci-cd',
              event_type: 'pr-check-trigger',
              client_payload: {
                ref: context.payload.pull_request.head.ref,
                pr_number: context.payload.pull_request.number
              }
            })
