name: branch-push
run-name: Run initated by ${{ github.actor }}
on:
  pull_request:
    branches:
      - main
      - sandbox
      - uat
      - dev
jobs:
  PR-checker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup python
        uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
      - name: Check lint with Ruff
        run: |
          pip install ruff
          ruff check .
      - name: List dirs
        run: ls
      - name: Test with logs
        shell: powershell
        run: |
          mkdir ${{ runner.temp }}/fuatilia/fuatilia/logs
          echo "Logs from building" > ${{ runner.temp }}/fuatilia/fuatilia/logs/test.log
      - name: Run Tests
        run: python app/manage.py test app/apps
      # - name: Run tests
      #   run: |
      #     pip install pytest pytest-cov
      #     pytest app/apps --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
