name: PR-merge
run-name: Run initated by ${{ github.actor }}
on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - uat
      - dev
jobs:
  Build-Api-Image:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image on PR
        run: docker build -t ${{secrets.DOCKERHUB_USERNAME}}/${{ github.base_ref }}-fuatilia-api .
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'docker.io/${{secrets.DOCKERHUB_USERNAME}}/${{ github.base_ref }}-fuatilia-api'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM'
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push Docker Image
        run: docker push ${{secrets.DOCKERHUB_USERNAME}}/${{ github.base_ref }}-fuatilia-api

  Deploy:
    # needs: Build-Image
    runs-on: self-hosted
    steps:
      - name: Remove env file and Copy vars
        # -f prevents non-zero exit status if file not there e.g on first run
        run: pwd && rm -f .env && echo "${{secrets.DEV_ENV_VARS}}" >> .env
      - name: Pull Swarm Configs
        run: cd deploy-config & git pull origin ${{ github.base_ref }}

      # - name: Pull fuatilia image
      #   run: sudo docker pull ${{secrets.DOCKERHUB_USERNAME}}/${{ github.base_ref }}-fuatilia-api
      # - name: Delete old container
      #   run: sudo docker rm -f ${{ github.base_ref }}-fuatilia-api
      # - name: Run Docker container
      #   run: sudo docker run -d -p 8000:8000 --name ${{ github.base_ref }}-fuatilia-api --env-file .env ${{secrets.DOCKERHUB_USERNAME}}/${{ github.base_ref }}-fuatilia-api
      # - name: Run docker stack
      #   run: docker stack deploy --compose-file -c docker-compose-dev.yml
