# Generated by Django 5.0.7 on 2024-08-08 18:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("bill_id", models.CharField(max_length=200)),
                ("representative_id", models.CharField(max_length=30)),
                (
                    "vote_type",
                    models.CharField(
                        choices=[
                            ("CONFIDENTIAL", "Confidential"),
                            ("CONCENSUS", "Concensus"),
                            ("INDIVIDUAL", "Individual"),
                        ],
                        default="INDIVIDUAL",
                        max_length=15,
                    ),
                ),
                ("vote_summary", models.JSONField(null=True)),
                ("house", models.CharField(max_length=10)),
                ("vote", models.CharField(max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["bill_id", "representative_id", "vote_type", "house"],
                        name="votes_vote_bill_id_216b33_idx",
                    )
                ],
            },
        ),
    ]
