# Generated by Django 5.1.1 on 2025-05-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("votes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="house",
            field=models.CharField(
                choices=[
                    ("NATIONAL", "National"),
                    ("SENATE", "Senate"),
                    ("ALL", "All"),
                ],
                max_length=10,
            ),
        ),
    ]
