# Generated by Django 5.1.1 on 2025-05-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("votes", "0002_alter_vote_house"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vote",
            name="bill_id",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="vote",
            name="representative_id",
            field=models.CharField(max_length=50),
        ),
    ]
